version: '3.4'

services:
  currencyconverterapi:
    container_name: ConverterApi
    image: currencyconverterapi
    build:
      context: .
      dockerfile: CurrencyConverterAPI/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - "5143:8080"
    networks:
        - dockernet

  cosmosdb:
    container_name: cosmosdb
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    tty: true
    restart: always
    ports:
        - "8081:8081"
    volumes:
        -  vol_cosmos:/data/db
    networks:
        - dockernet
        
networks:
    dockernet:
        driver: bridge

volumes:
    vol_cosmos:   
        driver: local